deployment:
  tasks:
    - export FRONT=/home/vivaiit/public_html
    - export APIAPP=/home/vivaiit/public_html/apiapp

    - /bin/mkdir -p $FRONT
    - /bin/mkdir -p $APIAPP

    - /bin/cp -R vivai/dist/. $FRONT
    - /bin/cp -R vivai-api/. $APIAPP